import type { TimelineTemplate } from '@/types'

export const TIMELINE_TEMPLATES: TimelineTemplate[] = [
  {
    id: 'research',
    name: 'Research Project',
    description: 'Track literature reviews, experiments, and findings',
    category: 'research',
    preview: '🔬',
    timeScale: 'month',
    defaultLanes: [
      { name: 'Literature Review', color: '#3b82f6', order: 0, isCollapsed: false },
      { name: 'Experiments', color: '#8b5cf6', order: 1, isCollapsed: false },
      { name: 'Analysis', color: '#06b6d4', order: 2, isCollapsed: false },
      { name: 'Writing', color: '#22c55e', order: 3, isCollapsed: false },
    ],
    defaultNodes: [
      { title: 'Literature Survey Start', priority: 'high', status: 'todo', color: '#3b82f6', tags: ['research', 'milestone'] },
      { title: 'Hypothesis Defined', priority: 'high', status: 'todo', color: '#8b5cf6', tags: ['milestone'] },
      { title: 'Experiment Design', priority: 'medium', status: 'todo', color: '#8b5cf6', tags: ['experiment'] },
      { title: 'Data Collection', priority: 'medium', status: 'todo', color: '#06b6d4', tags: ['data'] },
      { title: 'Analysis Complete', priority: 'high', status: 'todo', color: '#06b6d4', tags: ['milestone'] },
      { title: 'Draft Submission', priority: 'high', status: 'todo', color: '#22c55e', tags: ['deadline', 'milestone'] },
    ],
  },
  {
    id: 'story',
    name: 'Story / World Building',
    description: 'Map narrative arcs, characters, and plot events',
    category: 'story',
    preview: '📖',
    timeScale: 'custom',
    customScaleUnit: 'Chapter',
    defaultLanes: [
      { name: 'Main Plot', color: '#f59e0b', order: 0, isCollapsed: false },
      { name: 'Character Arc', color: '#ec4899', order: 1, isCollapsed: false },
      { name: 'World Events', color: '#6366f1', order: 2, isCollapsed: false },
    ],
    defaultNodes: [
      { title: 'Inciting Incident', priority: 'high', status: 'todo', color: '#f59e0b', tags: ['plot', 'milestone'] },
      { title: 'Hero\'s Journey Begins', priority: 'medium', status: 'todo', color: '#ec4899', tags: ['character'] },
      { title: 'First Act Break', priority: 'high', status: 'todo', color: '#f59e0b', tags: ['plot', 'milestone'] },
      { title: 'Midpoint Twist', priority: 'high', status: 'todo', color: '#f59e0b', tags: ['plot'] },
      { title: 'Dark Night of Soul', priority: 'high', status: 'todo', color: '#ec4899', tags: ['character'] },
      { title: 'Climax', priority: 'high', status: 'todo', color: '#f59e0b', tags: ['plot', 'milestone'] },
      { title: 'Resolution', priority: 'medium', status: 'todo', color: '#f59e0b', tags: ['plot'] },
    ],
  },
  {
    id: 'project',
    name: 'Software Project',
    description: 'Sprint planning, milestones, and release tracking',
    category: 'project',
    preview: '💻',
    timeScale: 'week',
    defaultLanes: [
      { name: 'Planning', color: '#64748b', order: 0, isCollapsed: false },
      { name: 'Development', color: '#3b82f6', order: 1, isCollapsed: false },
      { name: 'Testing', color: '#f59e0b', order: 2, isCollapsed: false },
      { name: 'Deployment', color: '#22c55e', order: 3, isCollapsed: false },
    ],
    defaultNodes: [
      { title: 'Project Kickoff', priority: 'high', status: 'todo', color: '#64748b', tags: ['milestone'] },
      { title: 'Sprint 1 Start', priority: 'medium', status: 'todo', color: '#3b82f6', tags: ['sprint'] },
      { title: 'MVP Feature Complete', priority: 'high', status: 'todo', color: '#3b82f6', tags: ['milestone'] },
      { title: 'QA Testing Phase', priority: 'high', status: 'todo', color: '#f59e0b', tags: ['testing'] },
      { title: 'Beta Release', priority: 'high', status: 'todo', color: '#22c55e', tags: ['release', 'milestone'] },
      { title: 'v1.0 Launch', priority: 'high', status: 'todo', color: '#22c55e', tags: ['release', 'milestone', 'deadline'] },
    ],
  },
  {
    id: 'history',
    name: 'Historical Timeline',
    description: 'Document historical events, eras, and periods',
    category: 'history',
    preview: '🏛️',
    timeScale: 'year',
    defaultLanes: [
      { name: 'Political', color: '#ef4444', order: 0, isCollapsed: false },
      { name: 'Cultural', color: '#f59e0b', order: 1, isCollapsed: false },
      { name: 'Scientific', color: '#3b82f6', order: 2, isCollapsed: false },
      { name: 'Economic', color: '#22c55e', order: 3, isCollapsed: false },
    ],
    defaultNodes: [
      { title: 'Era Begins', priority: 'high', status: 'todo', color: '#ef4444', tags: ['historical', 'milestone'] },
      { title: 'Key Political Event', priority: 'high', status: 'todo', color: '#ef4444', tags: ['historical', 'political'] },
      { title: 'Cultural Renaissance', priority: 'medium', status: 'todo', color: '#f59e0b', tags: ['historical', 'cultural'] },
      { title: 'Scientific Breakthrough', priority: 'medium', status: 'todo', color: '#3b82f6', tags: ['historical', 'innovation'] },
      { title: 'Era Ends', priority: 'high', status: 'todo', color: '#ef4444', tags: ['historical', 'milestone'] },
    ],
  },
]
